command:
  - uvicorn
  - src.main:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: DATABRICKS_HOST
    value: "dbc-2efb8509-0de6.cloud.databricks.com"
  - name: UC_CATALOG
    value: "plataforma"
  - name: UC_SCHEMA
    value: "default"
  - name: ENV
    value: "production"
  - name: SEG_EXEC_NOTEBOOK_PATH
    value: "/Workspace/Users/rafael.correr@bradesco.com.br/Testes/Loucura/databricks/jobs/s1_segmenthub/seg_exec"
  - name: SEG_EXEC_NOTEBOOK_PATH
    value: "/Workspace/Users/rafael.correr@bradesco.com.br/Testes/Loucura/databricks/jobs/s1_segmenthub/seg_exec"