build: false
command:
  - sh
  - -c
  - |
    echo "=== Iniciando build manual ==="
    cd frontend
    echo "📁 Diretório atual: $(pwd)"
    echo "📄 Conteúdo da pasta frontend:"
    ls -la
    echo "🧹 Instalando dependências..."
    npm install
    echo "🔨 Buildando o frontend..."
    npm run build
    echo "✅ Build concluído!"
    cd ..
    echo "🚀 Iniciando o servidor..."
    uvicorn src.main:app --host 0.0.0.0 --port 8000