-- ============================================================
-- ARQUIVO DESCONTINUADO — conteúdo migrado para 05_governanca_hist.sql
-- Mantido apenas para não quebrar referências de versão.
-- ============================================================
-- A tabela catalogo_governanca_hist é criada em 05_governanca_hist.sql.
-- Não execute este arquivo.